[package]
name = "nif_actions"
version = "0.1.0"
edition = "2024"

[lib]
name = "nif_actions"
crate-type = ["cdylib"]

[dependencies]
encoding_rs = "0.8.35"
rustler = "0.37.2"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

[workspace]
